syntax = "proto3";

option go_package = "zeno/pb";

package task;

message Task {
  string id = 1;
  string title = 2;
  bool completed = 3;
}

message SendTaskRequest {
  Task task = 1;
}

message SendTaskResponse {
  bool success = 1;
}
message ForwardCommandRequest {
    string command = 1; // "SET", "GET"
    repeated string args = 2; // ["key", "val"]
}

message ForwardCommandResponse {
    bool success = 1;
    string result = 2;
    string error = 3;
    string type = 4;
}

service NodeService {
    rpc ForwardCommand(ForwardCommandRequest) returns (ForwardCommandResponse);
}

service TaskService {
  rpc SendTask(SendTaskRequest) returns (SendTaskResponse);
}
